=== wotjd5101/assignment-1--databases--cs-365--fall-2023/xml/dtd/student.dtd
<!-- 
  Stduent_Information has two children; head and Student. However, since the Student elements are more than 2, the plus symbol is added to the end of Stduent.
   -->
   <!ELEMENT Student_Information (head, Student+)>
   <!-- 
     The head element refers to the project name, and #PCDATA reads the statements (project title)
      -->
   <!ELEMENT head (#PCDATA)>
   <!-- 
     Student element are the slibing with head, and has three childrens; Name, Information and CSS
      -->
   <!ELEMENT Student (Name, Information, CSS)>
   
   <!-- 
      Name element has five childrens 
      -->
   <!ELEMENT Name (First_name,Middle_name,Last_name,Preferred_name)>
   <!-- 
     The each element express a context in the index.xml scripts
      -->
   <!ELEMENT First_name (#PCDATA)>
   <!-- 
     it displays middle_name of the studnet. If they do not have it, it does not display from the file
      -->
   <!ELEMENT Middle_name (#PCDATA)>
   <!-- 
     it displays Last name of the studnet. 
      -->
   <!ELEMENT Last_name (#PCDATA)>
   <!-- 
     it displays Preferred_name of the studnet. If they do not have it, it does not display from the file
      -->
   <!ELEMENT Preferred_name (#PCDATA)>
   <!-- 
    Information have four children; Student_ID, Email, Phone, Status
      -->
   <!ELEMENT Information (Student_ID,Email,Phone,Status)>
   <!-- 
     it displays Student_ID of the studnet. 
      -->
   <!ELEMENT Student_ID (#PCDATA)>
   <!-- 
     it displays email of the studnet. 
      -->
   <!ELEMENT Email (#PCDATA)>
   <!-- 
     it displays phone number of the studnet. 
      -->
   <!ELEMENT Phone (#PCDATA)>
   <!-- 
     it displays status of the studnet. 
      -->
   <!ELEMENT Status (#PCDATA)>
   <!-- 
    CSS have seven children; GPA, Major, Minor, Current_Status, Advisor, Date, Graduation_date
      -->
   <!ELEMENT CSS (GPA, Major, Minor, Current_Status, Advisor, Date, Graduation_date)>
   <!-- 
     it displays GPA of the studnet. 
      -->
   <!ELEMENT GPA (#PCDATA)>
   <!-- 
     it displays Major of the studnet. 
      -->
   <!ELEMENT Major (#PCDATA)>
   <!-- 
     it displays minor of the studnet. 
      -->
   <!ELEMENT Minor (#PCDATA)>
   <!-- 
     it displays Current_Status of the studnet. 
      -->
   <!ELEMENT Current_Status (#PCDATA)>
   <!-- 
     it displays Advisor of the studnet. 
      -->
   <!ELEMENT Advisor (#PCDATA)>
   <!-- 
     it displays enrollment date of the studnet. 
      -->
   <!ELEMENT Date (#PCDATA)>
   <!-- 
     it displays graduation date of the studnet. 
      -->
   <!ELEMENT Graduation_date (#PCDATA)>
   
   <!-- 
     it declares attribue 'name' of element 'Student'. It is required attribute so that the user
     can find and recognize the student information in the easy way
      -->
   <!ATTLIST Student name CDATA #REQUIRED>

=== wotjd5101/assignment-1--databases--cs-365--fall-2023/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type = "text/css" href = "css/style.css"?>
<!DOCTYPE Student_Information SYSTEM "dtd/student.dtd">

<Student_Information>
  <head>Student Information</head>
  <Student name = "Gordon Matthew Sumner">

    <Name>
      <First_name>First Name: Gordon </First_name>
      <Middle_name>Middle Name: Matthew</Middle_name>
      <Last_name>Last Name: Sumner</Last_name>
      <Preferred_name>Preferred Name: "String"</Preferred_name>
    </Name>

    <Information>
      <Student_ID>Stduent ID: 1234567</Student_ID>
      <Email>Email: sting@thepolice.com</Email>
      <Phone>Phone Numer: 212.123.4567</Phone>
      <Status>Year: first year</Status>
    </Information>

    <CSS>
      <GPA>GPA:  4.0</GPA>
      <Major>Major: Music</Major>
      <Minor>Minor: English</Minor>
      <Current_Status>Current Status: Full-Time</Current_Status>
      <Advisor>Advisor: Andy Summers</Advisor>
      <Date>Date: 08-25-1969</Date>
      <Graduation_date>Graduation Date: 05-01-1973</Graduation_date>
    </CSS>

  </Student >

  <Student name = "Kim Thayilr">

    <Name>
      <First_name>First Name: Kim</First_name>
      <Middle_name/>
      <Last_name>Last Name: Thayilr</Last_name>
      <Preferred_name/>
    </Name>

    <Information>
      <Student_ID>Stduent ID: 4567890</Student_ID>
      <Email>Email: kim@soundgarden.com</Email>
      <Phone>Phone Numer: 206.123.4567</Phone>
      <Status>Year: second year</Status>
    </Information>

    <CSS>
      <GPA>GPA: 3.0</GPA>
      <Major>Major: Philosophy</Major>
      <Minor>Minor: Music</Minor>
      <Current_Status>Current Status: Full-Time</Current_Status>
      <Advisor>Advisor: Chris Cornell</Advisor>
      <Date>Date:  08-25-1978</Date>
      <Graduation_date>Graduation Date: 05-01-1982</Graduation_date>
    </CSS>

  </Student>


  <Student name = "Saul Hudson">

    <Name>
      <First_name>First Name: Saul</First_name>
      <Middle_name/>
      <Last_name>Last Name: Hudson</Last_name>
      <Preferred_name>Slash</Preferred_name>
    </Name>

    <Information>
      <Student_ID>Stduent ID: 8302438</Student_ID>
      <Email>Email: slash@gnr.com</Email>
      <Phone>Phone Numer: 213.456.8392</Phone>
      <Status>Year: fourth year</Status>
    </Information>

    <CSS>
      <GPA>GPA: 2.0</GPA>
      <Major>Major: Music</Major>
      <Minor>Minor: Criminal Justice</Minor>
      <Current_Status>Current Status: part-time</Current_Status>
      <Advisor>Advisor: Axl Rose</Advisor>
      <Date>Date: 08-25-1983</Date>
      <Graduation_date>Graduation Date: 05-01-1987</Graduation_date>
    </CSS>

  </Student>


  <Student name = "Emily Kokal">
    
    <Name>
      <First_name>First Name: Emily</First_name>
      <Middle_name/>
      <Last_name>Last Name: Kokal</Last_name>
      <Preferred_name/>
    </Name>

    <Information>
      <Student_ID>Stduent ID: 2983928</Student_ID>
      <Email>Email: emily@warpaint.com</Email>
      <Phone>Phone Numer: 213.123.7654</Phone>
      <Status>Year: third year</Status>
    </Information>

    <CSS>
      <GPA>GPA: 3.8</GPA>
      <Major>Major: Political Science</Major>
      <Minor>Minor: Law</Minor>
      <Current_Status>Current Status: full-time</Current_Status>
      <Advisor>Advisor: Jenny Lee Lindberg</Advisor>
      <Date>Date: 08-25-1998</Date>
      <Graduation_date>Graduation Date: 05-01-2002</Graduation_date>
    </CSS>

  </Student>

  <Student name = "Mike Inez">

    <Name>
      <First_name>First Name: Mike</First_name>
      <Middle_name/>
      <Last_name>Last Name: Inez</Last_name>
      <Preferred_name/>
    </Name>

    <Information>
      <Student_ID>Stduent ID: 7645726</Student_ID>
      <Email>Email: mike@aic.com</Email>
      <Phone>Phone Numer: 213.444.3323</Phone>
      <Status>Year: second year</Status>
    </Information>

    <CSS>
      <GPA>GPA: 4.0</GPA>
      <Major>Major: Business Management</Major>
      <Minor>Minor: Math</Minor>
      <Current_Status>Current Status: full-time</Current_Status>
      <Advisor>Advisor: Jerry Cantrell</Advisor>
      <Date>Date: 08-25-1984</Date>
      <Graduation_date>Graduation Date: 05-01-1988</Graduation_date>
    </CSS>

  </Student>
 </Student_Information>
